# Generated by Django 5.1.3 on 2024-12-03 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="householdtasktype",
            name="fimaly",
        ),
    ]
