# Generated by Django 5.1.3 on 2024-12-03 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_remove_householdtasktype_fimaly"),
    ]

    operations = [
        migrations.RenameField(
            model_name="householdtask",
            old_name="fimaly",
            new_name="family",
        ),
        migrations.RenameField(
            model_name="pointshistory",
            old_name="fimaly",
            new_name="family",
        ),
        migrations.RenameField(
            model_name="pointsredeem",
            old_name="fimaly",
            new_name="family",
        ),
        migrations.RenameField(
            model_name="redeemitem",
            old_name="fimaly",
            new_name="family",
        ),
        migrations.RenameField(
            model_name="taskcompletion",
            old_name="fimaly",
            new_name="family",
        ),
    ]
